version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=bncapi.settings
      - POSTGRES_DATABASE_URL=postgres://postgres:postgres@api-db:5432/bncapi_dev
      - POSTGRES_DB=bncapi_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=api-db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL_LAYER_URL=redis://redis:6379
      - PUBLIC_API_URL=http://localhost:8000/api
      - SECRET_KEY=my_precious_secret_key_for_local_prod
    depends_on:
      - api-db
      - redis
    networks:
      - app-network

  api-db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_DB=bncapi_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    restart: always
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
