# Generated by Django 5.2.4 on 2025-08-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="online",
        ),
        migrations.AddField(
            model_name="room",
            name="code_length",
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AddField(
            model_name="room",
            name="num_of_colors",
            field=models.IntegerField(blank=True, default=6),
        ),
        migrations.AddField(
            model_name="room",
            name="num_of_guesses",
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name="room",
            name="secret_code",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
