# Generated by Django 5.2.4 on 2025-08-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_remove_room_online_room_code_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="type",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
