# Generated by Django 5.2.4 on 2025-08-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_room_active_users_room_created_at_room_game_state_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="type",
            new_name="game_type",
        ),
    ]
