# Generated by Django 5.2.4 on 2025-08-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_rename_type_room_game_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameRoom",
        ),
    ]
