# Generated by Django 5.2.4 on 2025-08-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_delete_gameroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="secret_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
