# Generated by Django 5.2.4 on 2025-08-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_alter_room_secret_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="secret_code",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
